associate_mesh_FD_1D – openpde
associate_mesh_FD_1D Subroutine
Source File
public subroutine associate_mesh_FD_1D(mesh_input, calling_procedure, mesh_pointer)
Arguments
Type Intent Optional Attributes Name
class(mesh), intent(in), target :: mesh_input
Input mesh.
character(len=*), intent(in) :: calling_procedure
Name of the calling procedure.
class(mesh_FD_1D), intent(inout), pointer :: mesh_pointer
Finite Difference 1D mesh pointer.
Description
Check the type of the mesh passed as input and return a Finite Difference 1D mesh pointer associated to mesh.
Called By
Source Code
    subroutine associate_mesh_FD_1D(mesh_input, calling_procedure, mesh_pointer)
        !< Check the type of the mesh passed as input and return a Finite Difference 1D mesh pointer associated to mesh.
        class(mesh),       intent(in), target     :: mesh_input        !< Input mesh.
        character(*),      intent(in)             :: calling_procedure !< Name of the calling procedure.
        class(mesh_FD_1D), intent(inout), pointer :: mesh_pointer      !< Finite Difference 1D mesh pointer.
        select type(mesh_input)
            type is(mesh_FD_1D)
                mesh_pointer => mesh_input
            class default
               write(stderr, '(A)')' error: wrong mesh class'
               write(stderr, '(A)')' Calling procedure "'//calling_procedure//'"'
               stop
        end select
      end subroutine associate_mesh_FD_1D
Call graph
operate calls associate_mesh_fd_1d
bc calls associate_mesh_fd_1d
associate_mesh calls associate_mesh_fd_1d
init calls associate_mesh_fd_1d