associate_field_FD_1D – openpde
associate_field_FD_1D Subroutine
Source File
public subroutine associate_field_FD_1D(field_input, calling_procedure, field_pointer)
Arguments
Type Intent Optional Attributes Name
class(field), intent(in), target :: field_input
Input field.
character(len=*), intent(in) :: calling_procedure
Name of the calling procedure.
class(field_FD_1D), intent(inout), pointer :: field_pointer
Finite Difference 1D field pointer.
Description
Check the type of the field passed as input and return a Finite Difference 1D field pointer associated to field.
Called By
Source Code
    subroutine associate_field_FD_1D(field_input, calling_procedure, field_pointer)
        !< Check the type of the field passed as input and return a Finite Difference 1D field pointer associated to field.
        class(field),       intent(in), target     :: field_input       !< Input field.
        character(*),       intent(in)             :: calling_procedure !< Name of the calling procedure.
        class(field_FD_1D), intent(inout), pointer :: field_pointer     !< Finite Difference 1D field pointer.
        select type(field_input)
            type is(field_FD_1D)
                field_pointer => field_input
            class default
               write(stderr, '(A)')' error: wrong field class'
               write(stderr, '(A)')' Calling procedure "'//calling_procedure//'"'
               stop
        end select
      end subroutine associate_field_FD_1D
Call graph
operate calls associate_field_fd_1d
sub calls associate_field_fd_1d
add calls associate_field_fd_1d
realmul calls associate_field_fd_1d
mul calls associate_field_fd_1d
mulreal calls associate_field_fd_1d
assign_field calls associate_field_fd_1d
bc calls associate_field_fd_1d