associate_mesh_FD_1D_scalar – openpde
associate_mesh_FD_1D_scalar Function
13 statements
Source File
private function associate_mesh_FD_1D_scalar(mesh_input, emsg) result(mesh_pointer)
Check the type of the mesh passed as input and return a Finite Difference 1D mesh pointer associated to mesh.
Arguments
Type Intent Optional Attributes Name
class(mesh), intent(in), target :: mesh_input
Input mesh.
character(len=*), intent(in), optional :: emsg
Auxiliary error message.
Return Value class(mesh_FD_1D), pointer
Finite Difference 1D mesh pointer.
Called By
Source Code
associate_mesh_FD_1D_scalar
Source Code
    function associate_mesh_FD_1D_scalar(mesh_input, emsg) result(mesh_pointer)
        !< Check the type of the mesh passed as input and return a Finite Difference 1D mesh pointer associated to mesh.
        class(mesh),       intent(in), target   :: mesh_input    !< Input mesh.
        character(*),      intent(in), optional :: emsg          !< Auxiliary error message.
        class(mesh_FD_1D), pointer              :: mesh_pointer  !< Finite Difference 1D mesh pointer.
        select type(mesh_input)
            type is(mesh_FD_1D)
                mesh_pointer => mesh_input
            class default
               write(stderr, '(A)')'error: cast mesh to mesh_FD_1D'
               if (present(emsg)) write(stderr, '(A)') emsg
               stop
        end select
      end function associate_mesh_FD_1D_scalar
All Procedures
add add add add add add add alloc alloc assign_block assign_block assign_field assign_field assign_field assign_field assign_matrix assign_mesh_FD_1D assign_vector associate_field_FD_1D associate_field_FD_1D_rank1 associate_field_FD_1D_rank2 associate_field_FD_1D_scalar associate_field_FD_2D associate_field_FV_1D associate_field_surface_FV_1D associate_matrix_simple associate_mesh associate_mesh associate_mesh associate_mesh associate_mesh_FD_1D associate_mesh_FD_1D_rank1 associate_mesh_FD_1D_scalar associate_mesh_FD_2D associate_mesh_FV_1D associate_vector_simple bc_e bc_i compute_fluxes compute_fluxes create_subgrids_field div div div div div div free free free free free free free free free free free free free free free free free get init init init init init init init init init init init init init init init init init init integrate integrate integrate integrate jacobian load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json mul mul mul mul mul mul mulreal mulreal mulreal mulreal mulreal mulreal newrealmul operate operate operate operate operate operate operate operate operate operate operate operate operate output output output output output output output output output output output output realmul realmul realmul realmul realmul realmul realmul resid_e resid_emg resid_i set set set set set set set set set_matrix set_vector solve sub sub sub sub sub sub sub
Call graph
associate_mesh_fd_1d calls associate_mesh_fd_1d_scalar
operate calls associate_mesh_fd_1d
associate_mesh calls associate_mesh_fd_1d
init calls associate_mesh_fd_1d