associate_field_FD_1D_rank2 – openpde
associate_field_FD_1D_rank2 Function
13 statements
Source File
private function associate_field_FD_1D_rank2(field_input, emsg) result(field_pointer)
Check the type of the field passed as input and return a Finite Difference 1D field pointer associated to field.
Arguments
Type Intent Optional Attributes Name
class(field), intent(in), target :: field_input(:,:)
Input field.
character(len=*), intent(in), optional :: emsg
Auxiliary error message.
Return Value class(field_FD_1D), pointer,(:,:)
Finite Difference 1D field pointer.
Called By
Source Code
associate_field_FD_1D_rank2
Source Code
    function associate_field_FD_1D_rank2(field_input, emsg) result(field_pointer)
        !< Check the type of the field passed as input and return a Finite Difference 1D field pointer associated to field.
        class(field),       intent(in), target   :: field_input(:,:)   !< Input field.
        character(*),       intent(in), optional :: emsg               !< Auxiliary error message.
        class(field_FD_1D), pointer              :: field_pointer(:,:) !< Finite Difference 1D field pointer.
        select type(field_input)
            type is(field_FD_1D)
                field_pointer => field_input
            class default
               write(stderr, '(A)')'error: cast field to field_FD_1D'
               if (present(emsg)) write(stderr, '(A)') emsg
               stop
        end select
    end function associate_field_FD_1D_rank2
All Procedures
add add add add add add add alloc alloc assign_block assign_block assign_field assign_field assign_field assign_field assign_matrix assign_mesh_FD_1D assign_vector associate_field_FD_1D associate_field_FD_1D_rank1 associate_field_FD_1D_rank2 associate_field_FD_1D_scalar associate_field_FD_2D associate_field_FV_1D associate_field_surface_FV_1D associate_matrix_simple associate_mesh associate_mesh associate_mesh associate_mesh associate_mesh_FD_1D associate_mesh_FD_1D_rank1 associate_mesh_FD_1D_scalar associate_mesh_FD_2D associate_mesh_FV_1D associate_vector_simple bc_e bc_i compute_fluxes compute_fluxes create_subgrids_field dgetrf dgetrs div div div div div div free free free free free free free free free free free free free free free free free get init init init init init init init init init init init init init init init init init init integrate integrate integrate integrate jacobian load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json mul mul mul mul mul mul mulreal mulreal mulreal mulreal mulreal mulreal newrealmul operate operate operate operate operate operate operate operate operate operate operate operate operate output output output output output output output output output output output output realmul realmul realmul realmul realmul realmul realmul resid_e resid_emg resid_i set set set set set set set set set_matrix set_vector solve sub sub sub sub sub sub sub
Call graph
associate_field_fd_1d calls associate_field_fd_1d_rank2
integrate calls associate_field_fd_1d
operate calls associate_field_fd_1d
add calls associate_field_fd_1d
mulreal calls associate_field_fd_1d
mul calls associate_field_fd_1d
realmul calls associate_field_fd_1d
sub calls associate_field_fd_1d
assign_field calls associate_field_fd_1d
div calls associate_field_fd_1d
newrealmul calls associate_field_fd_1d