compute_fluxes – openpde
compute_fluxes Subroutine
15 statements
Source File
private subroutine compute_fluxes(this, field_cell, error)
Compute fluxes of field through surfaces.
Arguments
Type Intent Optional Attributes Name
class(field_surface_FV_1D), intent(inout) :: this
Fluxex.
class(field), intent(in) :: field_cell
Field at cells center.
integer(kind=I_P), intent(out), optional :: error
Error status.
Calls
Source Code
compute_fluxes
Source Code
    subroutine compute_fluxes(this, field_cell, error)
        !< Compute fluxes of field through surfaces.
        class(field_surface_FV_1D), intent(inout)         :: this           !< Fluxex.
        class(field),               intent(in)            :: field_cell     !< Field at cells center.
        integer(I_P),               intent(out), optional :: error          !< Error status.
        class(field_FV_1D), pointer                       :: field_cell_cur !< Dummy pointer for field at cells center.
        class(field_surface_FV_1D), pointer               :: flux_cur       !< Dummy pointer for fluxes.
        class(mesh_FV_1D), pointer                        :: mesh_cur       !< Dummy pointer for mesh.
        integer(I_P)                                      :: b              !< Counter.
        field_cell_cur => associate_field_FV_1D(field_input=field_cell, emsg='calling procedure field_surface_FV_1D%fluxes')
        mesh_cur => associate_mesh_FV_1D(mesh_input=field_cell_cur%m, emsg='calling procedure field_surface_FV_1D%fluxes')
        flux_cur => associate_field_surface_FV_1D(field_input=this, emsg='calling procedure field_surface_FV_1D%fluxes')
        do b=1, mesh_cur%nb
            call flux_cur%blocks(b)%compute_fluxes(field_cell=field_cell_cur%blocks(b), mesh_block=mesh_cur%blocks(b), error=error)
        end do
    end subroutine compute_fluxes
All Procedures
add add add add add add add alloc alloc assign_block assign_block assign_field assign_field assign_field assign_field assign_matrix assign_mesh_FD_1D assign_vector associate_field_FD_1D associate_field_FD_1D_rank1 associate_field_FD_1D_rank2 associate_field_FD_1D_scalar associate_field_FD_2D associate_field_FV_1D associate_field_surface_FV_1D associate_matrix_simple associate_mesh associate_mesh associate_mesh associate_mesh associate_mesh_FD_1D associate_mesh_FD_1D_rank1 associate_mesh_FD_1D_scalar associate_mesh_FD_2D associate_mesh_FV_1D associate_vector_simple bc_e bc_i compute_fluxes compute_fluxes create_subgrids_field dgetrf dgetrs div div div div div div free free free free free free free free free free free free free free free free free get init init init init init init init init init init init init init init init init init init integrate integrate integrate integrate jacobian load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json mul mul mul mul mul mul mulreal mulreal mulreal mulreal mulreal mulreal newrealmul operate operate operate operate operate operate operate operate operate operate operate operate operate output output output output output output output output output output output output realmul realmul realmul realmul realmul realmul realmul resid_e resid_emg resid_i set set set set set set set set set_matrix set_vector solve sub sub sub sub sub sub sub
Call graph
compute_fluxes calls associate_field_fv_1d, associate_field_surface_fv_1d, associate_mesh_fv_1d