operate – openpde
operate Function
18 statements
Source File
private function operate(this, inp, dir) result(opr)
Operator operation.
Arguments
Type Intent Optional Attributes Name
class(spatial_operator_d1_FD_1D), intent(in) :: this
The operator.
class(field), intent(in), target :: inp
Input field.
integer(kind=I_P), intent(in), optional :: dir
Direction of operation.
Return Value class(field), allocatable,target
Field resulting after the operator application.
Calls
Source Code
operate
Source Code
    function operate(this, inp, dir) result(opr)
        !< Operator operation.
        class(spatial_operator_d1_FD_1D), intent(in)           :: this     !< The operator.
        class(field),                     intent(in), target   :: inp      !< Input field.
        integer(I_P),                     intent(in), optional :: dir      !< Direction of operation.
        class(field), allocatable, target                      :: opr      !< Field resulting after the operator application.
        class(field_FD_1D), pointer                            :: inp_cur  !< Dummy pointer for input field.
        class(field_FD_1D), pointer                            :: opr_cur  !< Dummy pointer for operator result.
        class(mesh_FD_1D),  pointer                            :: mesh_cur !< Dummy pointer for mesh.
        integer(I_P)                                           :: i        !< Counter.
        allocate(field_FD_1D :: opr)
        opr_cur => associate_field_FD_1D(field_input=opr, emsg='calling procedure spatial_operator_d1_FD_1D%operate')
        inp_cur => associate_field_FD_1D(field_input=inp, emsg='calling procedure spatial_operator_d1_FD_1D%operate')
        mesh_cur => associate_mesh_FD_1D(mesh_input=inp%m, emsg='calling procedure spatial_operator_d1_FD_1D%operate')
        call opr_cur%associate_mesh(field_mesh=inp%m)
        do i=1, mesh_cur%n
            opr_cur%val(i) = (inp_cur%val(i+1) - inp_cur%val(i))/(mesh_cur%h)
        enddo
    end function operate
All Procedures
add add add add add add add alloc alloc assign_block assign_block assign_field assign_field assign_field assign_field assign_matrix assign_mesh_FD_1D assign_vector associate_field_FD_1D associate_field_FD_1D_rank1 associate_field_FD_1D_rank2 associate_field_FD_1D_scalar associate_field_FD_2D associate_field_FV_1D associate_field_surface_FV_1D associate_matrix_simple associate_mesh associate_mesh associate_mesh associate_mesh associate_mesh_FD_1D associate_mesh_FD_1D_rank1 associate_mesh_FD_1D_scalar associate_mesh_FD_2D associate_mesh_FV_1D associate_vector_simple bc_e bc_i compute_fluxes compute_fluxes create_subgrids_field div div div div div div free free free free free free free free free free free free free free free free free get init init init init init init init init init init init init init init init init init init integrate integrate integrate integrate jacobian load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json mul mul mul mul mul mul mulreal mulreal mulreal mulreal mulreal mulreal newrealmul operate operate operate operate operate operate operate operate operate operate operate operate operate output output output output output output output output output output output output realmul realmul realmul realmul realmul realmul realmul resid_e resid_emg resid_i set set set set set set set set set_matrix set_vector solve sub sub sub sub sub sub sub
Call graph
operate calls associate_field_fd_1d, associate_mesh_fd_1d
associate_field_fd_1d calls associate_field_fd_1d_scalar, associate_field_fd_1d_rank2, associate_field_fd_1d_rank1
associate_mesh_fd_1d calls associate_mesh_fd_1d_scalar, associate_mesh_fd_1d_rank1