operate – openpde
operate Function
24 statements
Source File
private function operate(this, fie) result(vec)
Operator operation.
Arguments
Type Intent Optional Attributes Name
class(f2v_FD_1D), intent(in) :: this
The operator.
class(field), intent(in), dimension(:), target :: fie
Input field.
Return Value class(vector), allocatable
Returned vector.
Calls
Source Code
operate
Source Code
    function operate(this, fie) result(vec)
        !< Operator operation.
        class(f2v_FD_1D), intent(in)       :: this     !< The operator.
        class(field), intent(in), dimension(:), target   :: fie      !< Input field.
        class(vector), allocatable         :: vec      !< Returned vector.
        class(field_FD_1D), pointer        :: fie_cur  !< Dummy pointer for input field.
        class(mesh_FD_1D),  pointer        :: mesh_cur !< Dummy pointer for mesh.
        integer(I_P)                       :: i        !< Counter.
        integer(I_P)                       :: i_equ        !< Counter.
        integer(I_P)                       :: i_vec        !< Counter.
        integer(I_P)                       :: n        !< Number of points.
        integer(I_P)                       :: n_equ        !< Number of points.
        n_equ = size(fie)
        mesh_cur => associate_mesh_FD_1D(mesh_input=fie(1)%m, emsg='mesh')
        n =  mesh_cur%n
        allocate(vec, mold=this%vec)
        call vec%init(n*n_equ)
        do i_equ = 1,n_equ
            fie_cur => associate_field_FD_1D(field_input=fie(i_equ), emsg='casting error')
            ! No concrete features of vector are used so dynamic casting is not needed
            do i=1, n
                i_vec = n*(i_equ-1)+i
            !    print*,"i, fie_cur%val(i) :",i, fie_cur%val(i)
                call vec%set(i_vec, fie_cur%val(i))
            enddo
        enddo
    end function operate
All Procedures
add add add add add add add alloc alloc assign_block assign_block assign_field assign_field assign_field assign_field assign_matrix assign_mesh_FD_1D assign_vector associate_field_FD_1D associate_field_FD_1D_rank1 associate_field_FD_1D_rank2 associate_field_FD_1D_scalar associate_field_FD_2D associate_field_FV_1D associate_field_surface_FV_1D associate_matrix_simple associate_mesh associate_mesh associate_mesh associate_mesh associate_mesh_FD_1D associate_mesh_FD_1D_rank1 associate_mesh_FD_1D_scalar associate_mesh_FD_2D associate_mesh_FV_1D associate_vector_simple bc_e bc_i compute_fluxes compute_fluxes create_subgrids_field div div div div div div free free free free free free free free free free free free free free free free free get init init init init init init init init init init init init init init init init init init integrate integrate integrate integrate jacobian load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json mul mul mul mul mul mul mulreal mulreal mulreal mulreal mulreal mulreal newrealmul operate operate operate operate operate operate operate operate operate operate operate operate operate output output output output output output output output output output output output realmul realmul realmul realmul realmul realmul realmul resid_e resid_emg resid_i set set set set set set set set set_matrix set_vector solve sub sub sub sub sub sub sub
Call graph
operate calls associate_mesh_fd_1d, associate_field_fd_1d
associate_mesh_fd_1d calls associate_mesh_fd_1d_scalar, associate_mesh_fd_1d_rank1
associate_field_fd_1d calls associate_field_fd_1d_scalar, associate_field_fd_1d_rank2, associate_field_fd_1d_rank1