solve – openpde
solve Subroutine
12 statements
Source File
private subroutine solve(this)
Solve the linear system.
Arguments
Type Intent Optional Attributes Name
class(linsolver_gmlapack), intent(inout), target :: this
Calls
Source Code
solve
Source Code
    subroutine solve(this)
        !< Solve the linear system.
        class(linsolver_gmlapack), intent(inout), target :: this
        integer(I_P)                              :: n
        class(matrix_simple), pointer             :: mat_cur
        class(vector_simple), pointer             :: vec_cur
        n = this%mat%n
        !debug print*,"allocated(this%mat): ",allocated(this%mat)
        !debug associate(v => this%mat)
        !debug select type(v)
        !debug     type is(matrix_simple)
        !debug         mat_cur => v
        !debug         print*,"allocated(this%mat%val): ",allocated(v%val)
        !debug         print*,"this%mat%val: ",v%val(:,:)
        !debug end select
        !debug end associate
        !debug associate(v => this%vec)
        !debug select type(v)
        !debug     type is(vector_simple)
        !debug         print*,"this%vec%val: ",v%val(:)
        !debug         vec_cur => v
        !debug end select
        !debug end associate
        vec_cur => associate_vector_simple(vector_input=this%vec)
        mat_cur => associate_matrix_simple(matrix_input=this%mat)
        ! Factorize matrix
        call dgetrf( n, n, mat_cur%val, this%lda, this%ipiv, this%info )
        ! Solver linear system
        call dgetrs( 'n', n, 1, mat_cur%val, this%lda, this%ipiv, vec_cur%val, n, this%info )
        ! Assign solution to sol vector
        this%sol = this%vec
        !debug associate(v => this%sol)
        !debug select type(v)
        !debug     type is(vector_simple)
        !debug         print*,"this%sol%val: ",v%val(:)
        !debug end select
        !debug end associate
    end subroutine solve
All Procedures
add add add add add add add alloc alloc assign_block assign_block assign_field assign_field assign_field assign_field assign_matrix assign_mesh_FD_1D assign_vector associate_field_FD_1D associate_field_FD_1D_rank1 associate_field_FD_1D_rank2 associate_field_FD_1D_scalar associate_field_FD_2D associate_field_FV_1D associate_field_surface_FV_1D associate_matrix_simple associate_mesh associate_mesh associate_mesh associate_mesh associate_mesh_FD_1D associate_mesh_FD_1D_rank1 associate_mesh_FD_1D_scalar associate_mesh_FD_2D associate_mesh_FV_1D associate_vector_simple bc_e bc_i compute_fluxes compute_fluxes create_subgrids_field div div div div div div free free free free free free free free free free free free free free free free free get init init init init init init init init init init init init init init init init init init integrate integrate integrate integrate jacobian load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json load_from_json mul mul mul mul mul mul mulreal mulreal mulreal mulreal mulreal mulreal newrealmul operate operate operate operate operate operate operate operate operate operate operate operate operate output output output output output output output output output output output output realmul realmul realmul realmul realmul realmul realmul resid_e resid_emg resid_i set set set set set set set set set_matrix set_vector solve sub sub sub sub sub sub sub
Call graph
solve calls dgetrf, dgetrs, associate_vector_simple, associate_matrix_simple